

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- feature/deploy

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: BuildConfiguration
  value: Release

stages:
- stage: Dev_Build
  displayName: Development Build
  jobs:
      - job:
        steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
                packageType: 'sdk'
                version: '3.1.402'
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '/p:DeployOnBuild=true  /p:PackageLocation="$(build.artifactStagingDirectory)"'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'            