

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: BuildConfiguration
  value: Release

stages:
- stage: Dev_Build
  displayName: Development Build
  jobs:
      - job:
        steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
                packageType: 'sdk'
                version: '3.1.402'
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '/p:DeployOnBuild=true  /p:PackageLocation="$(build.artifactStagingDirectory)"'
        - task: DotNetCoreCLI@2
          displayName: Publish        
          inputs:
            command: 'publish'
            publishWebProjects: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'  

        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: '4659b0a4-a29f-4fb9-bfa1-414c60f7821c/693b0d3c-d949-488d-ba85-5a980bd98a60'
            vstsFeedPackagePublish: 'dev'
            versionOption: 'patch'