

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- feature/deploy

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: BuildConfiguration
  value: Release

stages:
- stage: Dev_Build
  displayName: Development Build
  condition: containes(variable['Build.SourceBranch'],'feature/deploy')
  jobs:
      - job:
        steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
                packageType: 'sdk'
                version: '3.1.402'
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '/p:DeployOnBuild=true  /p:PackageLocation="$(build.artifactStagingDirectory)"'
        - task: DotNetCoreCLI@2
          displayName: Publish        
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--output $(Build.ArtifactStagingDirectory)'


        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'  

        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: '60676893-bec0-4972-bc19-f18a69038ab9/6f7493f5-6fc0-4507-bb68-1cb91ea63f9d'
            vstsFeedPackagePublish: 'dev'
            versionOption: 'patch'