name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- none

pool:
  vmImage: 'ubuntu-20.04'

variables:
 - group: demo-devtest
 - name: web_app_name
   value: "weatherman"
 - name: serviceplan_name
   value: "ASP-TestGroup-plan"
 - name: tf_version
   value: 0.14.9  

steps:
- checkout: self
  clean: true


- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
    backendServiceArm: 'ARM-Connect-DevTest'
    backendAzureRmResourceGroupName: 'TestGroup'
    backendAzureRmStorageAccountName: 'jmtestacct'
    backendAzureRmContainerName: 'jmtest'
    backendAzureRmKey: 'app_tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
    commandOptions: -var-file="$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service/variables.tfvars" -var subscription_id=$(subscription-id) -var client_id=$(client-id) -var client_secret=$(client-secret) -var tenant_id=$(tenant-id) -var app_name=$(web_app_name) -var app_plan=$(serviceplan_name) 
    environmentServiceNameAzureRM: 'ARM-Connect-DevTest'
