name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- none

pool:
  vmImage: 'ubuntu-20.04'

variables:
- ${{ if contains(variables['Build.SourceBranch'], 'feature/deploy') }}:
    - group: demo-devtest
    - template: ./env/test-vars.yml


steps:
- checkout: self
  clean: true

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
    backendServiceArm: $(azure_rm_svc) 
    backendAzureRmResourceGroupName: $(rg_name) #''
    backendAzureRmStorageAccountName: $(storage-account) #''
    backendAzureRmContainerName: $(storage-container) #''
    backendAzureRmKey: $(app_state) #''

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
    commandOptions: -var-file="$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service/variables.tfvars" -var subscription_id=$(subscription-id) -var client_id=$(client-id) -var client_secret=$(client-secret) -var tenant_id=$(tenant-id) -var app_name=$(web_app_name) -var app_plan=$(serviceplan_name) 
    environmentServiceNameAzureRM: $(azure_rm_svc)

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service'
    commandOptions: -var-file="$(System.DefaultWorkingDirectory)/IaC/azure-modules/app-service/variables.tfvars" -var subscription_id=$(subscription-id) -var client_id=$(client-id) -var client_secret=$(client-secret) -var tenant_id=$(tenant-id) -var app_name=$(web_app_name) -var app_plan=$(serviceplan_name) -auto-approve
    environmentServiceNameAzureRM: $(azure_rm_svc)